---
# - name: Update and upgrade packages
#   become: yes
#   apt:
#     upgrade: yes
#     update_cache: yes

# - name: Remove unuse dependencies
#   become: yes
#   apt:
#     autoremove: yes

# - name: Install NodeJS
#   become: yes
#   apt: 
#     name: nodejs
#     state: latest
- name: "Create DIR for Test"
  shell: |
    mkdir ~/backend-artifactII

- name: Creates directory
  become: true
  file:
    path: ~/backend-artifact
    state: directory

# - name: "Unarchive"
#   unarchive:
#     src: backend-artifact.tar.gz
#     dest: ~/backend-artifact

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-artifact
    npm install

# - name: "Executing Node app with PM2"
#   shell: |
#     cd ~/backend-artifact/dist    
#     pm2 stop default
#     pm2 start main.js
#   register: execute_node

# - name: print message
#   debug:
#     msg: "{{ execute_node.stdout_lines }}"

# - name: "Configure pm2 to start as service"
#   become: true
#   shell: |
#     env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu    