- name: Creates directory
  file:
    path: /home/ubuntu/backend-artifact
    state: directory

- name: "Unarchive"
  unarchive:
    src: .circleci/ansible/roles/deploy/files/artifact.tar.gz
    dest: /home/ubuntu/backend-artifact